// Lab6_Interrupts.c
// Starter file for CECS346 Lab 6
// By Dr. Min He
// 3/14/2024

#include "tm4c123gh6pm.h"
#include <stdint.h> // C99 data types

// 1. Pre-processor Directives Section
// Constant declarations to access port registers using 
// symbolic names instead of addresses

// TODO: define bit addresses for the three LEDs connected to PORTF
#define LED        (*((volatile uint32_t *)0x0))   
#define SW2        (*((volatile uint32_t *)0x0))   
	
// TODO: Define the three LED bit positions
#define RED  			0x00
#define BLUE 			0x00
#define GREEN			0x00
#define SW2_MASK  0x00

// TODO: define constants used in this project.
#define HALF_S 							0U          // Assume the system clock is 16MHz.
																				// define number of clock cycles to generate 0.5s time interval.
                                        // A U follows a constant indicate this is an unsigned number
#define NVIC_EN0_PORTF		  0x00000000  // bit position for PORTF interrupt in NVIC_EN0_R register.


// Function Prototypes (external functions from startup.s)
extern void DisableInterrupts(void); // Disable interrupts
extern void EnableInterrupts(void);  // Enable interrupts
extern void WaitForInterrupt(void);  // Go to low power mode while waiting for the next interrupt

// Function Prototypes
// Initialize rising edge triggered interrupt for PF0 (SW2) and three LEDs on Port F
void Switch_LED_Init(void);  

// Initialize SysTick timer with interrupt enabled.
// Parameter "period" specifies number of counts for the time 
// period generated by systick timer.
void SysTick_Init(uint32_t period);      

// global variable visible in Watch and Memory window of debugger:
// used for the purpose of practicing debug: use watch window and memory window 
// to keep track of varaible values and memory contents.
// This variable helps keeping track of number of button presses: 
// it increments once per button release.
volatile uint32_t RisingEdges = 0;

// keep track of the current active LED
volatile uint8_t curr_led = RED;

int main(void){
	DisableInterrupts();
  Switch_LED_Init();
	SysTick_Init(HALF_S);
	EnableInterrupts();
	
	// initialize current active LED to be red
	LED = RED;
	curr_led = RED;
	
  while(1){
		WaitForInterrupt();
  }
}


// TODO: Initialize rising edge triggered interrupt for PF0 (SW2) and three LEDs on Port F
void Switch_LED_Init(void) {
  
}

// TODO: Initialize SysTick timer with interrupt enabled.
// Parameter "period" specifies number of counts for the time 
void SysTick_Init(uint32_t period) {
}

// TODO: ISR that Handles GPIO Port F interrupts. 
// When Port F interrupt triggers, do what's necessary then increment global variable RisingEdges
void GPIOPortF_Handler(void) {
	// simple solution to take care of button debounce: 20ms to 30ms delay
  for (uint32_t i=0;i<160000;i++) {}	
}

// TODO: ISR that Handles SysTick generated interrupts. 
// When timer interrupt triggers, do what's necessary then toggle the current LED
void SysTick_Handler(void) {
}
